apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "revolt.fullname" . }}-web"
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "revolt.labels" . | nindent 4 }}
    revolt-app: {{ include "revolt.fullname" . }}-web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "revolt.selectorLabels" . | nindent 6 }}
      revolt-app: {{ include "revolt.fullname" . }}-web
  template:
    metadata:
      {{- with .Values.web.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        revolt-app: {{ include "revolt.fullname" . }}-web
        {{- include "revolt.labels" . | nindent 8 }}
        {{- with .Values.web.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: HOSTNAME
              value: 'https://{{ .Values.global.domain }}'
            - name: REVOLT_PUBLIC_URL
              value: 'https://{{ .Values.global.domain }}/api'
          livenessProbe:
            {{- if .Values.web.livenessProbe }}
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.web.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            {{- end }}
          readinessProbe:
            {{- if .Values.web.readinessProbe }}
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
            {{- else }}
            tcpSocket:
              port: {{ .Values.global.web.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            {{- end }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- with .Values.web.extra_volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "revolt.fullname" . }}-config
        {{- with .Values.web.extra_volumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
