apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoat.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stoat.labels" . | nindent 4 }}
    stoat-app: web
  {{- with (merge (.Values.global.all.service.annotations | default dict) (.Values.web.service.annotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.web.port }}
  selector:
    {{- include "stoat.selectorLabels" . | nindent 4 }}
    stoat-app: web
