apiVersion: v1
kind: Service
metadata:
  name: {{ include "revolt.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "revolt.labels" . | nindent 4 }}
    revolt-app: {{ include "revolt.fullname" . }}-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: {{ .Values.global.api.port }}
  selector:
    {{- include "revolt.selectorLabels" . | nindent 4 }}
    revolt-app: {{ include "revolt.fullname" . }}-api
